#162414258 Setup Postgres for Authors Haven
andela/neon-ah-backend pull request #12
Opened 2019-01-10 08:23 UTC by rafmme

#### What does this PR do?
This PR configures Authors Haven to use Postgres as Database engine

#### Description of Task to be Completed?
* Install Postgres on local manchine
* Create user neon on postgres
* Setup different database for both development and test environment 
* Add migration and seeding command to npm scripts on package.json
* Create a .sequelizerc file and configure paths for model, migrations and seeders directories
* Run sequelize init to create the directories in the path as above.
* Add dotenv file with database login credentials
* Add dotenv file to .gitignore

#### How should this be manually tested?
* Install postgres on your local machine
* Create postgres user neon and grant access for creating databases.
* Login with user neon and
* Create haven_dev as a local development database
* Create haven_test as a local test database
* Run ```npm install``` command to install pg, sequelize and sequelize-cli packages
* Run ```npm run db:migrate``` and `npm run db:seed`

#### What are the relavant pivotal tracker stories?
[Configure Authors Haven to use PostgreSQL as DB Engine](https://www.pivotaltracker.com/story/show/162414258)

2019-01-10 18:27 UTC, seunkoko requested changes

2019-01-10 18:27 UTC, seunkoko commented on .env.sample
> +DATABASE_URL_DEV = postgresql://neon:''@localhost:5432/haven_dev
The red arrow on the second line indicates there is no new line at the end of the file. Please fix this by adding an empty line below.

2019-01-10 19:05 UTC, rafmme commented on .env.sample
> +DATABASE_URL_DEV = postgresql://neon:''@localhost:5432/haven_dev
Alright, I have added a new line to the file

2019-01-10 20:58 UTC, Bobsar0 commented on .env.sample
> +DATABASE_URL_DEV = postgresql://neon:''@localhost:5432/haven_dev
Also, merge conflicts have been resolved.

2019-01-11 10:18 UTC, seunkoko approved these changes

2019-01-11 10:18 UTC, merged